-- Chips (keogan.ca/chips) — complete schema, consolidated from the original
-- poker-tracker migrations into one paste-ready script.
--
-- Run this once in the Supabase SQL editor of the site's project (the same
-- one that holds guestbook_entries). It only creates new objects; nothing
-- here touches the guestbook.
--
-- Covers, in order:
--   1. tables + lifetime_stats view
--   2. RLS with open anon policies (no accounts — the publishable key is safe
--      to expose; matches the guestbook's trust model)
--   3. explicit GRANTs — Supabase cloud stopped auto-granting new tables to
--      the Data API roles on 2026-05-30, so without these every query fails
--      with "permission denied"
--   4. realtime on sessions / players / events (live table updates)

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- tables

-- players_identity: one row per device (UUID kept in localStorage)
create table players_identity (
  id uuid primary key default gen_random_uuid(),
  display_name text,
  email text,
  created_at timestamptz not null default now()
);

-- sessions: one row per game
create table sessions (
  id uuid primary key default gen_random_uuid(),
  join_code text not null,
  status text not null default 'waiting',
  game_mode text not null default 'cash',
  host_player_id uuid,
  small_blind int not null default 1,
  big_blind int not null default 2,
  -- host-chosen buy-in; every joiner starts with exactly this stack
  starting_stack int not null default 200,
  blind_level int not null default 0,
  blind_level_started_at timestamptz,
  blind_schedule jsonb not null default '[]',
  -- do eliminations climb the blind ladder automatically? The schedule is always
  -- populated (it sets the starting blinds and backs the host's manual override),
  -- so this flag is what the setup toggle controls.
  -- Added 2026-07: existing databases need
  --   alter table sessions add column auto_escalate boolean not null default true;
  auto_escalate boolean not null default true,
  button_player_id uuid,
  current_actor_id uuid,
  current_bet int not null default 0,
  pot int not null default 0,
  street text not null default 'preflop'
    check (street in ('preflop', 'flop', 'turn', 'river', 'showdown')),
  created_at timestamptz not null default now(),
  last_active_at timestamptz
);

-- players: one row per seat per session
create table players (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  identity_id uuid references players_identity(id),
  display_name text not null,
  stack int not null default 0,
  total_buyin int not null default 0,
  is_host boolean not null default false,
  is_active boolean not null default true,
  folded boolean not null default false,
  current_round_bet int not null default 0,
  -- street the player last acted on; "acted this street" iff it equals
  -- sessions.street, so a street advance atomically invalidates everyone
  acted_on_street text,
  hand_total_bet int not null default 0,
  last_heartbeat_at timestamptz not null default now(),
  seat_order int not null default 0
);

-- player FKs on sessions (deferred to avoid the circular reference)
alter table sessions
  add constraint sessions_button_player_id_fkey
  foreign key (button_player_id) references players(id)
  deferrable initially deferred;

alter table sessions
  add constraint sessions_current_actor_id_fkey
  foreign key (current_actor_id) references players(id)
  on delete set null;

-- rebuys
create table rebuys (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  player_id uuid not null references players(id) on delete cascade,
  amount int not null,
  created_at timestamptz not null default now()
);

-- hands
create table hands (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references sessions(id) on delete cascade,
  pot_total int not null,
  winner_player_id uuid references players(id),
  ended_at timestamptz not null default now()
);

-- events: append-only activity log per session (the "ledger").
-- One row per notable action: blinds, bets, calls, checks, folds, street
-- transitions, wins, rebuys, and seat changes (join/leave/kick). `deal` rows
-- mark hand boundaries and are used to group the ledger by hand.
create table events (
  id uuid primary key default gen_random_uuid(),
  -- monotonic sequence for deterministic chronological ordering
  seq bigint generated by default as identity,
  session_id uuid not null references sessions(id) on delete cascade,
  -- null for system events (street transitions); set null if the player row is removed
  player_id uuid references players(id) on delete set null,
  type text not null,
  amount int,
  street text,
  -- recipient for 'give' (player-to-player chip transfer) events; null elsewhere.
  -- Added 2026-07: existing databases need
  --   alter table events add column target_player_id uuid
  --     references players(id) on delete set null;
  target_player_id uuid references players(id) on delete set null,
  created_at timestamptz not null default now()
);

create index events_session_seq_idx on events (session_id, seq);

-- lifetime_stats: per-identity aggregates over ended sessions.
--
-- Written as CREATE OR REPLACE so this statement is also the migration: re-run it
-- on an existing database to pick up new columns. Postgres only allows *appending*
-- columns to a replaced view, which is why times_first sits at the end rather than
-- next to times_last where it reads more naturally.
create or replace view lifetime_stats as
select
  pi.id as identity_id,
  pi.display_name,
  count(distinct p.session_id) as sessions_played,
  coalesce(sum(p.stack - p.total_buyin), 0) as total_net,
  coalesce(max(p.stack - p.total_buyin), 0) as biggest_win,
  -- Placement is by NET (stack − buy-in), never raw stack: with rebuys in play the
  -- biggest stack at the table can belong to the night's biggest loser — three rebuys
  -- deep and up from their last one is still down overall. Same grading as the
  -- placement column in analytics-export.sql. A tie counts for everyone level at the
  -- bottom (and times_first treats a tie at the top the same way).
  count(*) filter (
    where p.stack - p.total_buyin = (
      select min(p2.stack - p2.total_buyin)
      from players p2
      where p2.session_id = p.session_id
    )
  ) as times_last,
  coalesce(sum(p.total_buyin), 0) as total_buyin,
  -- Sessions this player finished with the best net result at the table.
  count(*) filter (
    where p.stack - p.total_buyin = (
      select max(p2.stack - p2.total_buyin)
      from players p2
      where p2.session_id = p.session_id
    )
  ) as times_first
from players_identity pi
join players p on p.identity_id = pi.id
join sessions s on s.id = p.session_id and s.status = 'ended'
group by pi.id, pi.display_name;

-- session_results: one row per player per ended session — the per-night grain the
-- lifetime board can't show. Backs the net chart (cumulative net over time) and the
-- chaos score (volatility of a player's results).
--
-- Like lifetime_stats this is CREATE OR REPLACE so the statement doubles as its own
-- migration; re-run it on an existing database to add the view.
--
-- net_bb normalises a night's result to big blinds. Raw net is not comparable across
-- stakes — a 5/10 tournament dwarfs a 1/2 cash game — so anything that averages or
-- takes a standard deviation across nights must use net_bb, not net.
create or replace view session_results as
select
  p.identity_id,
  coalesce(pi.display_name, p.display_name)                                  as display_name,
  s.id                                                                      as session_id,
  s.created_at,
  s.big_blind,
  p.stack - p.total_buyin                                                   as net,
  round((p.stack - p.total_buyin)::numeric / nullif(s.big_blind, 0), 2)     as net_bb
from players p
join sessions s on s.id = p.session_id and s.status = 'ended'
left join players_identity pi on pi.id = p.identity_id
where p.identity_id is not null;

-- Extended per-player statistics (VPIP, PFR, c-bet, steal, WTSD, positional splits)
-- live in a separate file, supabase/player-stats.sql, because they are a few hundred
-- lines of ledger reconstruction and have nothing to do with making the game work.
-- Run that file too if you want the `player_stats` view; nothing here depends on it.

-- ------------------------------------------------------------------- RLS

alter table players_identity enable row level security;
alter table sessions enable row level security;
alter table players enable row level security;
alter table rebuys enable row level security;
alter table hands enable row level security;
alter table events enable row level security;

create policy "anon full access" on players_identity for all to anon using (true) with check (true);
create policy "anon full access" on sessions for all to anon using (true) with check (true);
create policy "anon full access" on players for all to anon using (true) with check (true);
create policy "anon full access" on rebuys for all to anon using (true) with check (true);
create policy "anon full access" on hands for all to anon using (true) with check (true);
create policy "anon full access" on events for all to anon using (true) with check (true);

-- ---------------------------------------------------------------- grants

-- Table-level privileges for the Data API roles. RLS alone is not enough —
-- without these GRANTs the anon role gets "permission denied for table …".
-- (Identity columns need no separate sequence grant.)
grant all on table players_identity, sessions, players, rebuys, hands, events
  to anon, authenticated, service_role;
grant select on lifetime_stats, session_results to anon, authenticated, service_role;

-- -------------------------------------------------------------- realtime

-- Stream row changes so every phone at the table updates live. The app
-- subscribes to postgres_changes on exactly these three tables.
alter publication supabase_realtime add table sessions;
alter publication supabase_realtime add table players;
alter publication supabase_realtime add table events;
